//============================================================================
/// @file calculator.idl
///
                                                           //qidl copyright
//% Copyright (c) 2012-2014 Qualcomm Technologies, Inc.
                                                           //qidl nested=false
//% All Rights Reserved.
//% Qualcomm Confidential and Proprietary
//============================================================================

#include "AEEStdDef.idl"
#include "remote.idl"

interface calculator : remote_handle64{
    AEEResult sum(in sequence<long> vec, rout long long res);
    AEEResult remap(
        in sequence<unsigned long> pRemapTable0,
        in sequence<unsigned long> pRemapTable1,
        in sequence<unsigned long> pRemapTable2,
        in sequence<unsigned long> pRemapTable3,
        in sequence<uint8> inputBuffer,
        rout sequence<uint8> outBuffer
    );
};